// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "hw3"
)

func main() {
  g := gen.NewGenerator("fast_easyjson.go")
  g.SetPkg("hw3", "hw3")
  g.Add(pkg.EasyJSON_exporter_myUser(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
